### ISSUE TITLE
MAVUtil connection errors

### ISSUE THREAD

**Issue by wfehrnstrom** [uas-at-ucla/suas_2018#13]
Running Python2.7 under pipenv with all the required dependencies installed through pip_requirements.txt, I receive the following error message on running test_control.

`test_commander (__main__.TestControl) ... Connecting to drone at tcp:127.0.0.1:5760
[Errno 61] Connection refused sleeping
os: osx, apm: copter, release: stable
[Errno 22] Invalid argument sleeping
SITL already Downloaded and Extracted.
Ready to boot.
Execute: /Users/wfehrnstrom/.dronekit/sitl/copter-3.3/apm --home 0.0,0.0,0.0,0 --instance 0 --model=quad
Started model quad at 0.0,0.0,0.0,0 at speed 1.0
bind port 5760 for 0
Starting sketch 'ArduCopter'
Serial port 0 on TCP port 5760
Starting SITL input
Waiting for connection ....
ERROR
test_copter_interface_init (__main__.TestControl) ... DRONE ADDRESS
tcp:127.0.0.1:5760
Connecting to drone at tcp:127.0.0.1:5760
[Errno 61] Connection refused sleeping
os: osx, apm: copter, release: stable
SITL already Downloaded and Extracted.
Ready to boot.
Execute: /Users/wfehrnstrom/.dronekit/sitl/copter-3.3/apm --home 0.0,0.0,0.0,0 --instance 0 --model=quad
Started model quad at 0.0,0.0,0.0,0 at speed 1.0
bind port 5760 for 0
Starting sketch 'ArduCopter'
Serial port 0 on TCP port 5760
Starting SITL input
Waiting for connection ....
[Errno 22] Invalid argument sleeping
ERROR
test_copter_interface_takeoff_and_land (__main__.TestControl) ... Connecting to drone at tcp:127.0.0.1:5760
[Errno 61] Connection refused sleeping
os: osx, apm: copter, release: stable
SITL already Downloaded and Extracted.
Ready to boot.
Execute: /Users/wfehrnstrom/.dronekit/sitl/copter-3.3/apm --home 0.0,0.0,0.0,0 --instance 0 --model=quad
Started model quad at 0.0,0.0,0.0,0 at speed 1.0
bind port 5760 for 0
Starting sketch 'ArduCopter'
Serial port 0 on TCP port 5760
Starting SITL input
Waiting for connection ....
[Errno 22] Invalid argument sleeping
ERROR

======================================================================
ERROR: test_commander (__main__.TestControl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_control.py", line 32, in test_commander
    copter = commander.Commander(drone_address)
  File "/Users/wfehrnstrom/Desktop/suas_2018/control/commander/commander.py", line 26, in __init__
    self.copter = copter_interface.CopterInterface(drone_address)
  File "/Users/wfehrnstrom/Desktop/suas_2018/control/flight_control/copter_interface.py", line 338, in __init__
    self.vehicle = self.__connect_to_drone(address)
  File "/Users/wfehrnstrom/Desktop/suas_2018/control/flight_control/copter_interface.py", line 355, in __connect_to_drone
    wait_ready = True)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/dronekit/__init__.py", line 2835, in connect
    handler = MAVConnection(ip, baud=baud, source_system=source_system, use_native=use_native)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/dronekit/mavlink.py", line 128, in __init__
    self.master = mavutil.mavlink_connection(ip, baud=baud, source_system=source_system)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/pymavlink/mavutil.py", line 1209, in mavlink_connection
    return mavtcp(device[4:], source_system=source_system, retries=retries, use_native=use_native)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/pymavlink/mavutil.py", line 945, in __init__
    self.port.connect(self.destination_addr)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 22] Invalid argument

======================================================================
ERROR: test_copter_interface_init (__main__.TestControl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_control.py", line 45, in test_copter_interface_init
    copter = copter_interface.CopterInterface(drone_address)
  File "/Users/wfehrnstrom/Desktop/suas_2018/control/flight_control/copter_interface.py", line 338, in __init__
    self.vehicle = self.__connect_to_drone(address)
  File "/Users/wfehrnstrom/Desktop/suas_2018/control/flight_control/copter_interface.py", line 355, in __connect_to_drone
    wait_ready = True)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/dronekit/__init__.py", line 2835, in connect
    handler = MAVConnection(ip, baud=baud, source_system=source_system, use_native=use_native)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/dronekit/mavlink.py", line 128, in __init__
    self.master = mavutil.mavlink_connection(ip, baud=baud, source_system=source_system)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/pymavlink/mavutil.py", line 1209, in mavlink_connection
    return mavtcp(device[4:], source_system=source_system, retries=retries, use_native=use_native)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/pymavlink/mavutil.py", line 945, in __init__
    self.port.connect(self.destination_addr)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 22] Invalid argument

======================================================================
ERROR: test_copter_interface_takeoff_and_land (__main__.TestControl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_control.py", line 72, in test_copter_interface_takeoff_and_land
    copter = copter_interface.CopterInterface(drone_address)
  File "/Users/wfehrnstrom/Desktop/suas_2018/control/flight_control/copter_interface.py", line 338, in __init__
    self.vehicle = self.__connect_to_drone(address)
  File "/Users/wfehrnstrom/Desktop/suas_2018/control/flight_control/copter_interface.py", line 355, in __connect_to_drone
    wait_ready = True)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/dronekit/__init__.py", line 2835, in connect
    handler = MAVConnection(ip, baud=baud, source_system=source_system, use_native=use_native)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/dronekit/mavlink.py", line 128, in __init__
    self.master = mavutil.mavlink_connection(ip, baud=baud, source_system=source_system)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/pymavlink/mavutil.py", line 1209, in mavlink_connection
    return mavtcp(device[4:], source_system=source_system, retries=retries, use_native=use_native)
  File "/Users/wfehrnstrom/.virtualenvs/suas_2018-NKyQkke1/lib/python2.7/site-packages/pymavlink/mavutil.py", line 945, in __init__
    self.port.connect(self.destination_addr)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 22] Invalid argument

----------------------------------------------------------------------
Ran 3 tests in 6.045s

FAILED (errors=3)`

**Comment by comran** [comment]
I think we fixed this with the sleep delay?

**Comment by wfehrnstrom** [comment]
The sleep delay fixed the issue.
